# Clean up

In [2]:
import pandas as pd

In [3]:
HISTORICAL_DATASET = "/Users/shishiraravindan/Documents/FSB_coding_files/scrapingProject/2_salaries/faculty-wage-consolidation/UoI_wageDataset_1993-2023.xlsx"
CLEANED_DATASET = "/Users/shishiraravindan/Documents/FSB_coding_files/scrapingProject/2_salaries/faculty-wage-consolidation/UoI_wageDataset_completeCleaned.xlsx"

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [5]:
# I want to read the excel file in this directory called a.xlsx and show the header
def read_excel_file(file_name):
    """
    Reads an Excel file (.xlsx) from the current directory,
    loads it into a pandas DataFrame, and prints the header.

    Parameters:
        file_name (str): Name of the Excel file to be loaded.
    """
    df = pd.read_excel(file_name)
    display(df.head(5))
    return df

In [10]:
historical_df = read_excel_file(HISTORICAL_DATASET)
historical_df.shape

,Year,Name,Gender,Agency,City/Country,Class,Salary1,Salary2,Travel,Department
0,2023,"AAMODT,JAMES",M,UNIVERSITY OF IOWA,JOHNSON,TEMP PROFESSIONAL EMPLOYEE,0,"4,486.00",0,NaN
1,2023,"ABBAS,PAUL J",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR EMERITUS,0,"13,496.00",0,NaN
2,2023,"ABDEL WAHED,LAMA",F,UNIVERSITY OF IOWA,JOHNSON,CLINICAL ASSISTANT PROFESSOR,172448,"186,433.00",2313,NaN
3,2023,"ABDEL-MALEK,KARIM",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR,302106,"379,681.00",2278,NaN
4,2023,"ABEL,EDWIN G",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR,381758,"417,869.00",34377,NaN

(276750, 10)

In [9]:
cleaned_df = read_excel_file(CLEANED_DATASET)
cleaned_df.shape

,Year,Name,Gender,Agency,City/Country,Class,Salary1,Salary2,Travel,Department
0,2023,"ABBAS,PAUL J",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR EMERITUS,0,"13,496.00",0,COMMUNICATION SCI AND DISORDER
1,2023,"ABDEL WAHED,LAMA",F,UNIVERSITY OF IOWA,JOHNSON,CLINICAL ASSISTANT PROFESSOR,172448,"186,433.00",2313,NEURO-NEUROLOGY CLINIC
2,2023,"ABDEL-MALEK,KARIM",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR,302106,"379,681.00",2278,Mechanical Engineering
3,2023,"ABOUL HOSN,MAEN S",M,UNIVERSITY OF IOWA,JOHNSON,CLINICAL ASSISTANT PROFESSOR,51081,"116,477.00",0,VASCULAR
4,2023,"ABRAMOFF,MICHAEL DAVID",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR,32226,"36,997.00",0,PSYCHIATRY

(11280, 10)

In [11]:
# Rename the column in the dataframes to Rank
historical_df = historical_df.rename(columns={'Class': 'Rank'})
cleaned_df = cleaned_df.rename(columns={'Class': 'Rank'})

In [13]:
updateCount = 0
for index, row in cleaned_df.iterrows():
    name, dept = row['Name'], row['Department']
    mask = historical_df['Name'] == name
    updateMask = mask & historical_df['Department'].isna()
    historical_df.loc[updateMask, 'Department'] = dept
    updateCount += updateMask.sum()
print(updateCount)

/var/folders/jp/m2c1zn6d3tb0k3w11rrd6f2w0000gn/T/ipykernel_92810/1801819421.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'COMMUNICATION SCI AND DISORDER' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  historical_df.loc[updateMask, 'Department'] = dept

11280

In [14]:
display(historical_df.head(20))

,Year,Name,Gender,Agency,City/Country,Rank,Salary1,Salary2,Travel,Department
0,2023,"AAMODT,JAMES",M,UNIVERSITY OF IOWA,JOHNSON,TEMP PROFESSIONAL EMPLOYEE,0,"4,486.00",0,NaN
1,2023,"ABBAS,PAUL J",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR EMERITUS,0,"13,496.00",0,COMMUNICATION SCI AND DISORDER
2,2023,"ABDEL WAHED,LAMA",F,UNIVERSITY OF IOWA,JOHNSON,CLINICAL ASSISTANT PROFESSOR,172448,"186,433.00",2313,NEURO-NEUROLOGY CLINIC
3,2023,"ABDEL-MALEK,KARIM",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR,302106,"379,681.00",2278,Mechanical Engineering
4,2023,"ABEL,EDWIN G",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR,381758,"417,869.00",34377,NaN
5,2023,"ABOU ALAIWA,MAHMOUD HASAN",M,UNIVERSITY OF IOWA,JOHNSON,ASSISTANT PROFESSOR,213619,"209,924.00",3036,NaN
6,2023,"ABOU-ARAB,EMAD",M,UNIVERSITY OF IOWA,WASHTENAW,CLINICAL ASSISTANT PROFESSOR,0,"29,847.00",0,NaN
7,2023,"ABOUL HOSN,MAEN S",M,UNIVERSITY OF IOWA,JOHNSON,CLINICAL ASSISTANT PROFESSOR,51081,"116,477.00",0,VASCULAR
8,2023,"ABRAHAM,MOLLY SUSAN",F,UNIVERSITY OF IOWA,JOHNSON,TEMP PROFESSIONAL EMPLOYEE,0,"1,382.00",0,NaN
9,2023,"ABRAM,NANCY J",F,UNIVERSITY OF IOWA,JOHNSON,ASSOCIATE PROFESSOR OF PRACTIC,87075,"87,700.00",1284,NaN
10,2023,"ABRAM,SAVANNAH G",F,UNIVERSITY OF IOWA,JOHNSON,TEMP PROFESSIONAL EMPLOYEE,0,"6,056.00",0,NaN
11,2023,"ABRAMOFF,MICHAEL DAVID",M,UNIVERSITY OF IOWA,JOHNSON,PROFESSOR,32226,"36,997.00",0,PSYCHIATRY
12,2023,"ABRAMS,THAD EUGENE",M,UNIVERSITY OF IOWA,JOHNSON,CLINICAL ASSOCIATE PROFESSOR,9490,"37,536.00",1347,INTERNAL MEDICINE
13,2023,"ABRAMSON,DEAN ALAN",M,UNIVERSITY OF IOWA,LINN,CLINICAL ASSOCIATE PROFESSOR,256599,"254,469.00",0,GASTROENTEROLOGY/HEP
14,2023,"ABREU,LUIS MANUEL",M,UNIVERSITY OF IOWA,JOHNSON,TEMP PROFESSIONAL EMPLOYEE,0,"1,806.00",0,NaN
15,2023,"ABRONS,JEANINE PORTER",F,UNIVERSITY OF IOWA,WARREN,CLINICAL ASSOCIATE PROFESSOR,69844,"72,905.00",1899,APPLIED CLINICAL SCIENCES
16,2023,"ABRONS,RON OWEN",M,UNIVERSITY OF IOWA,WARREN,VISITING ASSOCIATE PROFESSOR,0,"1,900.00",0,ANESTHESIA
17,2023,"ABU HEJLEH,TAHER",M,UNIVERSITY OF IOWA,JOHNSON,CLINICAL PROFESSOR,0,"206,719.00",0,ANESTHESIA
18,2023,"ABUHAMMOUD,SALAHALDEEN MOHAMMAD ASSAD",M,UNIVERSITY OF IOWA,JOHNSON,ASSISTANT PROFESSOR,129211,"136,824.00",1165,Dentistry
19,2023,"ABURIZIK,ARWA",F,UNIVERSITY OF IOWA,JOHNSON,CLINICAL ASSOCIATE PROFESSOR,282748,"314,217.00",0,INTERNAL MEDICINE

In [28]:
import re

def replace_department(dept):
    if isinstance(dept, str):
        if re.search(r'\bFinance\b', dept, re.IGNORECASE):
            return 'FIN'
        elif re.search(r'\bBusiness Administration\b', dept, re.IGNORECASE):
            return 'BUSI'
    return dept

historical_df['Department'] = historical_df['Department'].apply(replace_department)

In [31]:
# Merging tippie data to dataset
tippie_df = pd.read_excel('tippie.xlsx')

updateCount = 0
for index, row in tippie_df.iterrows():
    name, dept = row['Name'], row['Faculty']
    print(f"{index} | {name}")
    mask = historical_df['Name'] == name
    updateMask = mask & historical_df['Department'].isna()
    historical_df.loc[updateMask, 'Department'] = dept
    updateCount += updateMask.sum()
print(updateCount)

0 | AMIR,RABAH
1 | BASCIFTCI,BESTE
2 | CAMPION,EMILY
3 | CHAKRABORTY,GOUTAM
4 | DORESCA,DIMY
5 | FAN,WEIGUO
6 | FITCHETT,JANALEE
7 | GALONI,CHELSEA
8 | GARLICK,JULIA
9 | HOUGE,TODD
10 | ILERISOY,MAHMUT
11 | JANDA,SWINDER
12 | JONES,KEITH
13 | KALNINS,ARTURS
14 | KARWAN,KIRK
15 | LEE,HYEONG-TAK
16 | LI,WEI
17 | LI,WEI
18 | LIE,ERIK
19 | LIN,QIHANG
20 | NAIN,AMRITA
21 | NAYAKANKUPPAM,DHANANJAY
22 | NEWTON,DANIEL
23 | NICA,ALEXANDRA
24 | OLSON,ERIC
25 | PETER,RICHARD
26 | QUINTO,CLAIRE
27 | RHODES,ADRIENNE
28 | RUAN,BOWEN
29 | SA-AADU,JARJISU
30 | SHAO,YIDUO
31 | SIMON,ROBERT
32 | SINAGL,PETRA
33 | SONG,SUYONG
34 | SRINIVASAN,PADMINI
35 | SU,RONG
36 | SUN,MINJEE
37 | THYROFF-FITZWATER,ANASTASIA
38 | TIWARI,ASHISH
39 | VELLIQUETTE,ANNE
40 | WANG,DANYE
41 | WILLIAMS,MICHELE
42 | XU,JIAJIE
43 | YAO,TONG
44 | ZHAO,KANG
224

In [32]:
historical_df['Department'] = historical_df['Department'].fillna('MISSING')

In [33]:
historical_df.to_csv('uoi-dataset.csv')

In [34]:
historical_df.to_excel('UoI-wage-dataset-1993-2023.xlsx')

In [39]:
dept_to_count = ['FIN', 'BUSI', 'ACC', 'ECO']
dept_counts = historical_df['Department'].value_counts()
specific_dept_counts = dept_counts[dept_counts.index.isin(dept_to_count)]
print("Department counts:")
for dept, count in specific_dept_counts.items():
    print(f"{dept}: {count}")

# Print total count
total_count = specific_dept_counts.sum()
print(f"\nTotal count of FIN, BUSI, ACC, and ECO departments: {total_count}")

Department counts:
BUSI: 116
FIN: 106
ECO: 26
ACC: 7

Total count of FIN, BUSI, ACC, and ECO departments: 255

In [40]:
filled_df = historical_df[historical_df['Department'] != 'MISSING']
len(filled_df)

11504

In [47]:
f1 = '/Users/shishiraravindan/Downloads/emeritusIowa.xlsx'
f2 = '/Users/shishiraravindan/Downloads/UoI-wage-dataset-1993-2023v2.xlsx'

In [48]:
df_business = pd.read_excel(f1)
df_main = pd.read_excel(f2)
updatesMade = 0

In [49]:
print(f"Orginial filled: {len(df_main[df_main['Department']!='MISSING'])}")

Orginial filled: 14520

In [54]:
for index, entry in df_business.iterrows():
        name = entry['Name']
        dept = entry['Department']
        mask = (df_main['Name'] == name & df_main['Name'] == 'MISSING')
        if not df_main.loc[mask].empty:  
            old_dept = df_main.loc[mask, 'Department'].iloc[0]
            print(old_dept)
            if old_dept != dept: 
                updatesMade += 1
                print(f'NAME: {name} | OLD: {old_dept} | NEW: {dept}')

        df_main.loc[mask, 'Department'] = dept
        print(f'{index}')

Business
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
Business
16
17
18
19
20
21
Business
22
23
Business
24
25
Business
26
Business
27
28
29
30
Business
31
32
33
34
35
Business
OLD: Business | NEW: Accounting
36
37
38
39
40
41
42
Dentistry
43
44
45
46
Dentistry
47
Dentistry
48
49
50
51
52
Dentistry
53
54
Dentistry
55
56
Medicine
57
Dentistry
58
59
60
61
62
63
64
65
66
67
68
69
70
Dentistry
71
72
73
74
Dentistry
75
76
Dentistry
77
78
79
Dentistry
80
81
82
Dentistry
83
84
85
Dentistry
86
87
88
89
90
91
92
Oral Pathology, Radiology, & Medicine
OLD: Oral Pathology, Radiology, & Medicine | NEW: Dentistry
93
94
Dentistry
95
96
97
98
99
100
Dentistry
101
102
Dentistry
103
104
Dentistry
105
106
107
Dentistry
108
109
110
111
112
113
114
115
116
117
118
119
120
121
Education
122
123
124
125
126
127
128
Education
129
130
Education
131
132
133
134
Education
135
Education
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
Education
154
155
156
157
Education
158
159
160
Education
161
Education
162
163
Education
164
Education
165
166
167
168
169
Physics
OLD: Physics | NEW: Engineering
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
Electrical and Computer Engineering
OLD: Electrical and Computer Engineering | NEW: Engineering
187
Mechanical Engineering
OLD: Mechanical Engineering | NEW: Engineering
188
189
Electrical and Computer Engineering
OLD: Electrical and Computer Engineering | NEW: Engineering
190
Mechanical Engineering
OLD: Mechanical Engineering | NEW: Engineering
191
192
193
194
Biomedical Engineering
OLD: Biomedical Engineering | NEW: Engineering
195
196
Mechanical Engineering
OLD: Mechanical Engineering | NEW: Engineering
197
198
Engineering
199
200
201
202
203
Industrial and Systems Engineering
OLD: Industrial and Systems Engineering | NEW: Engineering
204
205
206
207
208
209
210
211
212
213
Communication Studies
OLD: Communication Studies | NEW: Graduate College
214
215
Graduate College
216
217
218
219
220
221
222
law
OLD: law | NEW: Law
223
224
law
OLD: law | NEW: Law
225
226
227
228
229
230
231
Law
232
233
234
235
236
237
238
239
240
Law
241
242
law
OLD: law | NEW: Law
243
244
245
246
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Musicology
247
248
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Music Therapy
249
250
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Chemistry
251
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Geoscience
252
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Comparative Literature
253
254
255
256
257
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Music (Brass, Horn Performance)
258
259
260
261
262
263
264
265
266
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Dance
267
268
269
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: English
270
271
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Spanish and Portuguese
272
273
274
275
276
277
278
279
280
281
282
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: French
283
284
Mathematics
285
286
287
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Musicology
288
289
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Business Administration
290
291
292
Liberal Arts and Sciences
293
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Spanish and Portuguese
294
295
296
297
298
299
300
301
302
Communication Studies
303
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: History
304
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
305
306
307
308
309
310
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
311
Liberal Arts and Sciences
312
313
314
315
316
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Journalism
317
318
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: English
319
320
321
322
323
324
Computer Science
OLD: Computer Science | NEW: Liberal Arts and Sciences
325
326
327
328
329
330
331
332
333
334
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Cinema
335
Liberal Arts and Sciences
336
Communication Studies
OLD: Communication Studies | NEW: Liberal Arts and Science
337
338
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
339
340
Social Work
341
342
343
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Geography
344
345
346
347
348
349
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
350
351
352
353
354
355
356
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
357
Statistics and Actuarial Science
OLD: Statistics and Actuarial Science | NEW: Statistics
358
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: American Studies
359
360
361
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
362
363
364
Linguistics
365
366
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
367
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
368
369
370
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: English
371
372
373
374
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Philosophy
375
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
376
377
378
379
380
381
382
383
384
385
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
386
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
387
388
Computer Science
389
390
391
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Geography
392
393
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
394
395
396
397
398
399
400
401
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Art and Art History
402
403
Social Work
404
405
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Music
406
407
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
408
Foreign Languages, Literatures, and Linguistics
OLD: Foreign Languages, Literatures, and Linguistics | NEW: Asian and Slavic Languages and Literatures
409
Social Sciences
OLD: Social Sciences | NEW: Anthropology
410
411
412
413
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Psychology
414
Social Work
OLD: Social Work | NEW: Liberal Arts and Science
415
416
417
418
419
420
421
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Art History
422
423
424
425
426
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Sociology
427
428
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
429
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
430
431
432
433
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Asian and Slavic Languages and Literatures
434
435
436
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Statistics
437
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Political Science
438
439
440
441
442
443
Computer Science
444
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Psychology
445
446
447
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Chemistry
448
449
450
451
Linguistics
452
453
454
455
456
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Mathematics
457
458
459
460
461
462
463
464
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
465
466
467
468
469
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Physics and Astronomy
470
471
472
473
474
475
476
477
478
479
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Art and Art History
480
481
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: History
482
483
484
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
485
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: English
486
Social Sciences
OLD: Social Sciences | NEW: Anthropology
487
488
Liberal Arts and Sciences
489
490
Liberal Arts and Sciences
491
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
492
Biology
493
494
495
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Mathematics
496
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: History
497
498
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Spanish and Portuguese
499
Mathematics
500
501
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: English
502
503
504
505
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
506
507
508
509
510
511
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Political Science
512
513
514
515
516
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Theatre Arts
517
518
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: English
519
520
521
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: English
522
523
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Music
524
525
526
527
Social Sciences
OLD: Social Sciences | NEW: Anthropology
528
529
530
531
532
533
534
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Theatre Arts
535
536
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: German
537
538
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Music
539
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
540
541
542
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Philosophy
543
544
545
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Social Work
546
Biology
547
548
549
Biology
550
551
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Art and Art History
552
553
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: History
554
555
556
557
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
558
559
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
560
561
562
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Liberal Arts and Science
563
Computer Science
OLD: Computer Science | NEW: Liberal Arts and Science
564
565
566
567
568
569
570
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Spanish and Portuguese
571
572
573
574
575
576
577
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Art and Art History
578
579
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Physics and Astronomy
580
581
Biology
OLD: Biology | NEW: Liberal Arts and Science
582
583
584
585
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Biology
586
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Art and Art History
587
Biology
588
589
590
591
592
593
594
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Art and Art History
595
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Statistics
596
597
598
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Mathematics
599
600
law
OLD: law | NEW: History
601
602
603
604
605
Computer Science
606
607
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Art and Art History
608
609
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Communication Sciences and Disorders
610
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Communication Sciences and Disorders
611
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Music
612
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Anthropology
613
Computer Science
OLD: Computer Science | NEW: Mathematics
614
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: English
615
Social Work
616
Liberal Arts and Sciences
OLD: Liberal Arts and Sciences | NEW: Geoscience
617
618
619
Medicine
620
621
Medicine
622
Neurology
OLD: Neurology | NEW: Medicine
623
624
Medicine
625
Medicine
626
Medicine
627
Medicine
628
Medicine
629
Medicine
630
Medicine
631
632
Medicine
633
Medicine
634
Medicine
635
Medicine
636
637
Medicine
638
639
640
Medicine
641
Medicine
642
643
Medicine
644
Medicine
645
Pharmacology
OLD: Pharmacology | NEW: Medicine
646
Medicine
647
Medicine
648
Medicine
649
Medicine
650
Medicine
651
Medicine
652
653
Medicine
654
Medicine
655
Medicine
656
657
658
Medicine
659
660
Medicine
661
Medicine
662
Medicine
663
664
665
666
Medicine
667
Medicine
668
669
670
671
672
Neurology
OLD: Neurology | NEW: Medicine
673
674
675
676
Medicine
677
678
679
Neurology
OLD: Neurology | NEW: Medicine
680
681
682
683
684
685
Medicine
686
Medicine
687
Medicine
688
689
690
691
692
Medicine
693
Medicine
694
695
Medicine
696
Medicine
697
698
699
700
701
702
Medicine
703
704
705
706
707
708
709
Medicine
710
Medicine
711
Medicine
712
713
714
715
716
717
718
719
720
Medicine
721
722
723
724
725
726
727
728
Medicine
729
730
731
732
733
734
735
736
Medicine
737
738
739
740
741
742
743
744
745
Medicine
746
747
748
749
Medicine
750
751
Medicine
752
753
754
755
756
Medicine
757
758
759
760
761
762
763
764
765
766
767
768
Medicine
769
Medicine
770
771
772
773
774
775
776
777
778
779
780
Medicine
781
782
783
784
785
786
787
Medicine
788
789
Medicine
790
791
792
Medicine
793
794
795
796
797
798
799
800
Medicine
801
802
803
804
805
Medicine
806
807
808
809
Medicine
810
811
812
813
814
Medicine
815
816
817
Surgery-Surgical Oncology and Endocrine Surgery
OLD: Surgery-Surgical Oncology and Endocrine Surgery | NEW: Medicine
818
819
Medicine
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
Medicine
841
Medicine
842
843
844
845
Medicine
846
Neurology
OLD: Neurology | NEW: Medicine
847
Medicine
848
849
850
851
Medicine
852
853
Medicine
854
Medicine
855
Medicine
856
Neurology
OLD: Neurology | NEW: Medicine
857
Medicine
858
Medicine
859
Medicine
860
861
862
863
864
865
866
Medicine
867
Medicine
868
Medicine
869
870
871
Medicine
872
Medicine
873
874
875
Medicine
876
877
Medicine
878
879
880
Medicine
881
882
883
884
885
Medicine
886
887
888
Medicine
889
890
891
892
893
894
895
896
897
Medicine
898
899
Medicine
900
901
902
903
904
Medicine
905
Medicine
906
907
908
909
910
911
Medicine
912
913
914
915
916
917
Medicine
918
919
920
Medicine
921
Medicine
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
Medicine
943
Neurology
OLD: Neurology | NEW: Medicine
944
945
Medicine
946
Medicine
947
948
949
Medicine
950
951
952
Medicine
953
954
955
Neurology
OLD: Neurology | NEW: Medicine
956
957
958
959
960
961
962
963
Medicine
964
965
966
Medicine
967
968
969
Nursing
970
971
972
973
974
975
976
977
978
Nursing
979
980
981
982
983
984
985
Nursing
986
987
988
989
Nursing
990
991
Nursing
992
993
994
995
996
Nursing
997
998
Nursing
999
1000
1001
1002
1003
1004
1005
Nursing
1006
1007
Nursing
1008
1009
1010
1011
1012
Nursing
1013
Nursing
1014
1015
1016
Nursing
1017
1018
1019
1020
1021
Pharmacy
1022
1023
Pharmacy
1024
1025
Pharmacy
1026
1027
1028
1029
1030
1031
1032
Pharmacy
1033
1034
1035
1036
1037
1038
Pharmacy
1039
1040
1041
1042
Pharmacy
1043
1044
1045
Public Health
1046
1047
Public Health
1048
1049
Public Health
1050
Public Health
1051
Public Health
1052
1053
Public Health
1054
1055
1056
Public Health
1057
1058
1059
1060
1061
1062
Public Health
1063
1064
1065
Public Health
1066
Public Health
1067
Public Health
1068
Public Health
1069
1070
1071
1072
1073
Public Health
1074
1075
1076
Public Health
1077
Public Health
1078

In [55]:
print(updatesMade)
print(f"Updated: {len(df_main[df_main['Department']!='MISSING'])}")

126
Updated: 14520

In [56]:
df_main.to_excel('UoI-wage-dataset-1993-2023v3.xlsx', index=False)

In [46]:
def merge_emiritus_data(f1, f2):
    df_business = pd.read_excel(f1)
    df_main = pd.read_excel(f2)
    
    updatesMade = 0

    print(f"Orginial filled: {len(df_main[df_main['Department']!='MISSING'])}")
    #now update loop through the business data and update the main data
    for index, entry in df_business.iterrows():
        name = entry['Name']
        dept = entry['Department']
        mask = (df_main['Name'] == name)
        old_dept = df_main.loc[mask, 'Department']
        if old_dept != dept: 
            updatesMade += 1
            print(f'OLD: {old_dept} | NEW: {dept}')

        df_main.loc[mask, 'Department'] = dept
        print(f'{index}')


    # df_main.loc[df_main['Department']=='FIN', 'Department'] = "Finance"
    # df_main.loc[df_main['Department']=='BUSI', 'Department'] = "Business"
    # df_main.loc[df_main['Department']=='ACC', 'Department'] = "Accounting"
    # df_main.loc[df_main['Department']=='ECO', 'Department'] = "Economics"
    df_main.to_excel('UoI-wage-dataset-1993-2023v3.xlsx', index=False)
    
    print(f"Updated: {len(df_main[df_main['Department']!='MISSING'])}")


merge_emiritus_data(f1, f2)

Orginial filled: 14520

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().